// Generates idempotent upsert SQL for the KB reference tables from the typed
// seed data in data/kb/*, after validating every row against the Zod schemas.
// Run via `pnpm kb:sql` (writes .seed-kb.sql, git-ignored); apply with
// `pnpm kb:seed:local` / `pnpm kb:seed:remote`.
import { writeFileSync } from 'node:fs'
import { ulid } from 'ulid'
import { BANKS } from '../data/kb/banks'
import { CARDS } from '../data/kb/cards'
import { CATEGORIES } from '../data/kb/categories'
import {
  bankSchema,
  cardSchema,
  earnRuleSchema,
  categorySchema,
  categoryAccount,
  cardAccount,
  poolAccount,
  CARD_ACCOUNT_RE,
  REWARDS_ACCOUNT_RE,
} from '../src/lib/kb/schema'

const q = (s: string) => `'${s.replaceAll("'", "''")}'`
const now = Date.now()
const lines: string[] = ['-- generated by scripts/seed-kb.ts — do not edit by hand']

// --- validate ---------------------------------------------------------------
const banks = BANKS.map((b) => bankSchema.parse(b))
const categories = CATEGORIES.map((c) => categorySchema.parse(c))
const catSlugs = new Set(categories.map((c) => c.slug))
const bankBySlug = new Map(banks.map((b) => [b.slug, b]))

for (const { card, rules } of CARDS) {
  const c = cardSchema.parse(card)
  const bank = bankBySlug.get(c.bankSlug)
  if (!bank) throw new Error(`card ${c.slug}: unknown bank ${c.bankSlug}`)
  const acct = cardAccount(bank, c)
  if (!CARD_ACCOUNT_RE.test(acct)) throw new Error(`card ${c.slug}: bad account ${acct}`)
  if (!REWARDS_ACCOUNT_RE.test(poolAccount(bank)))
    throw new Error(`card ${c.slug}: bad pool account`)
  if (rules.length === 0) throw new Error(`card ${c.slug}: needs at least one earn rule`)
  for (const raw of rules) {
    const r = earnRuleSchema.parse(raw)
    for (const a of r.accelerators) {
      if (a.category && !catSlugs.has(a.category))
        throw new Error(`card ${c.slug}: accelerator references unknown category ${a.category}`)
    }
    for (const x of r.exclusions) {
      if (!catSlugs.has(x)) throw new Error(`card ${c.slug}: exclusion references unknown category ${x}`)
    }
  }
}

// --- emit -------------------------------------------------------------------
for (const b of banks) {
  lines.push(
    `INSERT INTO kb_banks (slug, name, beancount_name, updated_at) VALUES (${q(b.slug)}, ${q(b.name)}, ${q(b.beancountName)}, ${now})
  ON CONFLICT(slug) DO UPDATE SET name=excluded.name, beancount_name=excluded.beancount_name, updated_at=excluded.updated_at;`,
  )
}

for (const c of categories) {
  lines.push(
    `INSERT INTO kb_categories (slug, name, root, leaf, account, sort) VALUES (${q(c.slug)}, ${q(c.name)}, ${q(c.root)}, ${c.leaf ? q(c.leaf) : 'NULL'}, ${q(categoryAccount(c))}, ${c.sort})
  ON CONFLICT(slug) DO UPDATE SET name=excluded.name, root=excluded.root, leaf=excluded.leaf, account=excluded.account, sort=excluded.sort;`,
  )
}

for (const { card, rules } of CARDS) {
  lines.push(
    `INSERT INTO kb_cards (slug, bank_slug, name, beancount_name, network, pool_ticker, pool_programme, active, updated_at)
  VALUES (${q(card.slug)}, ${q(card.bankSlug)}, ${q(card.name)}, ${q(card.beancountName)}, ${card.network ? q(card.network) : 'NULL'}, ${q(card.pool.ticker)}, ${q(card.pool.programme)}, ${card.active ? 1 : 0}, ${now})
  ON CONFLICT(slug) DO UPDATE SET bank_slug=excluded.bank_slug, name=excluded.name, beancount_name=excluded.beancount_name, network=excluded.network, pool_ticker=excluded.pool_ticker, pool_programme=excluded.pool_programme, active=excluded.active, updated_at=excluded.updated_at;`,
  )
  for (const r of rules) {
    const parsed = earnRuleSchema.parse(r)
    lines.push(
      `INSERT INTO kb_earn_rules (id, card_slug, effective_from, rule_json, created_at)
  VALUES (${q(ulid())}, ${q(card.slug)}, ${q(parsed.effectiveFrom)}, ${q(JSON.stringify(parsed))}, ${now})
  ON CONFLICT(card_slug, effective_from) DO UPDATE SET rule_json=excluded.rule_json;`,
    )
  }
}

writeFileSync('.seed-kb.sql', lines.join('\n') + '\n')
console.log(
  `[seed-kb] wrote .seed-kb.sql — ${banks.length} banks, ${categories.length} categories, ${CARDS.length} cards, ${CARDS.reduce((n, c) => n + c.rules.length, 0)} rules`,
)
